steps:
  - id: Branch Validation
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - '-c'
      - |
          if [ $(git rev-parse --abbrev-ref HEAD) != "master" ]; then
            echo "Build aborted: Branch is $(git rev-parse --abbrev-ref HEAD)"
          else
            echo "Build success: Branch is $(git rev-parse --abbrev-ref HEAD)"
          fi
options:
  logging: CLOUD_LOGGING_ONLY
