steps:
  - id: Branch Validation
    name: 'ubuntu'
    entrypoint: bash
    args:
      - '-c'
      - |
          if [ "$BRANCH_NAME" != "master" ]; then
            echo "Build aborted: Branch is not master"
            echo "##############"
            echo $BRANCH_NAME
            echo "##############"
            git branch
            echo "##############"
            git rev-parse --symbolic-full-name HEAD
            echo "##############"
            env
          fi
options:
  logging: CLOUD_LOGGING_ONLY
