steps:
  - id: Branch Validation
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    env:
      - 'BRANCH=$(git rev-parse --abbrev-ref HEAD)'
    args:
      - '-c'
      - |
          # GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$BRANCH" != "master" ]; then
            echo "Build aborted: Branch is $BRANCH"
          else
            echo "Build success: Branch is $BRANCH"
          fi
options:
  logging: CLOUD_LOGGING_ONLY
