steps:
  - id: Branch Validation
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - '-c'
      - |
          if [ "$BRANCH_NAME" != "master" ]; then
            echo "Build aborted: Branch is not master"
            echo $BRANCH_NAME
            exit 1
          fi
options:
  logging: CLOUD_LOGGING_ONLY
