steps:
  - id: Branch Validation
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - '-c'
      - |
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> branch_info.txt
          cat branch_info.txt
options:
  logging: CLOUD_LOGGING_ONLY
