steps:
  - id: Branch Validation
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - '-c'
      - |
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $BUILD_WORKSPACE/branch_info.txt
          cat $BUILD_WORKSPACE/branch_info.txt
options:
  logging: CLOUD_LOGGING_ONLY
