steps:
  - id: Branch Validation
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - '-c'
      - |
          # GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$_GIT_BRANCH" != "master" ]; then
            echo "Build aborted: Branch is $_GIT_BRANCH"
          else
            echo "Build success: Branch is $_GIT_BRANCH"
          fi
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _GIT_BRANCH: $(git rev-parse --abbrev-ref HEAD)
